# Generated by Django 3.2 on 2021-04-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(max_length=50)),
                ('user_token', models.CharField(max_length=500)),
                ('fixture_id', models.CharField(max_length=250)),
                ('notification_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.CharField(max_length=250)),
                ('full_time_result', models.CharField(max_length=50)),
                ('half_time_result', models.CharField(max_length=50)),
                ('kick_off', models.CharField(max_length=50)),
                ('red_cards', models.CharField(max_length=50)),
                ('yellow_cards', models.CharField(max_length=50)),
                ('goals', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=50)),
            ],
        ),
    ]
