# Generated by Django 3.2 on 2021-04-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cronlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpriority',
            name='user_id',
            field=models.CharField(default='no_user', max_length=250),
        ),
        migrations.AlterField(
            model_name='notificationpriority',
            name='fixture_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notificationpriority',
            name='full_time_result',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notificationpriority',
            name='goals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notificationpriority',
            name='half_time_result',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notificationpriority',
            name='kick_off',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notificationpriority',
            name='red_cards',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notificationpriority',
            name='yellow_cards',
            field=models.IntegerField(),
        ),
    ]
