# Generated by Django 3.2 on 2021-04-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210420_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(default=0, max_length=250)),
                ('notification_status', models.CharField(default='NOT_SENT', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='notificationpriority',
            name='notification_id',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
