# Generated by Django 3.2 on 2021-04-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210421_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('fixture_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
