FULL_TIME = 1
HALF_TIME = 2
KICK_OFF = 3
RED_CARDS = 4
YELLOW_CARDS = 5
GOALS = 6

SENT = 'SENT'
NOT_SENT = 'NOT_SENT'
MATCH_STARTED = 'Match Started'
MATCH_FINISHED = 'Match Finished'

CARD = 'Card'
GOAL = 'Goal'

YELLOW_CARD = 'Yellow Card'
RED_CARD = 'Red Card'
